const actions = {
    LOAD_PRODUCTS: "LOAD_PRODUCTS",
    LOAD_PRODUCTS_SUCCESS: "LOAD_PRODUCTS_SUCCESS",
    LOAD_PRODUCTS_FAILURE: "LOAD_PRODUCTS_FAILURE",
    LOAD_PURCHASES: "LOAD_PURCHASES",
    LOAD_PURCHASES_SUCCESS: "LOAD_PURCHASES_SUCCESS",
    LOAD_PURCHASES_FAILURE: "LOAD_PURCHASES_FAILURE",
    UPDATE_PURCHASES: "UPDATE_PURCHASES"
};
export default actions;